version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent
      - 8989:8989 # Sonarr
      - 9696:9696 # Prowlarr
      - 7878:7878 # Radarr
      - 5055:5055 # Jellyseer
      - "7359:7369/udp" # Jellyfin
      - "8096:8096/tcp" # Jellyfin

    volumes:
      - /home/michael/docker/arr-stack/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=ivpn
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=<YOUR_PRIVATE_KEY> # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md#obtain-your-wireguard-private-key
      # - WIREGUARD_ADDRESSES=10.5.0.2/32
      # Timezone for accurate log times
      - TZ=America/Toronto
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - SERVER_CITIES=Toronto,Montreal
      - UPDATER_PERIOD=24h

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - WEBUI_PORT=8085
    volumes:
      - /home/michael/docker/arr-stack/qbittorrent:/config
      - /home/michael/media/downloads:/downloads
    depends_on:
      - gluetun
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/michael/docker/arr-stack/sonarr/data:/config
      - /home/michael/media/television:/television #optional
      - /home/michael/media/downloads:/downloads #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/michael/docker/arr-stack/radarr/data:/config
      - /home/michael/media/movies:/movies
      - /home/michael/media/downloads:/downloads

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/michael/docker/arr-stack/prowlarr/data:/config
    restart: unless-stopped

  jellyseerr:
     image: fallenbagel/jellyseerr:latest
     container_name: jellyseerr
     network_mode: "service:gluetun"
     environment:
          - LOG_LEVEL=debug
          - PUID=1000
          - PGID=1000
          - TZ=America/Toronto
     volumes:
          - /home/michael/docker/arr-stack/jellyseer:/app/config
     restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "service:gluetun"

    user: 1000:1000
    volumes:
      - /home/michael/docker/arr-stack/jellyfin/config:/config
      - /home/michael/docker/arr-stack/jellyfin/cache:/cache
      - /home/michael/media/movies:/movies
      - /home/michael/media/television:/television
    restart: 'unless-stopped'

