version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    ports:
      - "7359:7369/udp"
      - "8096:8096/tcp"
    volumes:
      - type: bind
        source: /home/michael/Jellyfin/config
        target: /config
      - type: bind
        source: /home/michael/Jellyfin/cache
        target: /cache
      - type: bind
        source: /home/michael/vg_data_1/Movies
        target: /movies
    restart: 'unless-stopped'
